README.md
dns/cloudflare.py
run.py

添加CloudFlare支持，照葫芦画瓢写了一下（因为我个人是用CloudFlare的，之前自己写了一个很不优雅的DDNS程序（嗯现在还在我的仓库里，然后觉得大佬好厉害，所以就直接搬到这里来了23333
在config的index4/6中添加‘none’选项，这个是因为现在如果想要禁用ipv4或ipv6的解析更新，就必须把config中的ipv4/ipv6那项中的域名全部删除，否则就会报网络不可达错误。对于用户（其实是我23333）来说，一个禁用选项比删除掉所有域名更方便

添加CloudFlare支持+一个小feature

---

util/ip.py

$ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
link/ether 00:15:5d:0f:87:07 brd ff:ff:ff:ff:ff:ff
inet 30.57.177.145/24 brd 30.57.177.255 scope global noprefixroute dynamic eth0
valid_lft 23131sec preferred_lft 23131sec
inet6 fe80::65b6:1c2d:e0ff:f2bf/64 scope link noprefixroute
valid_lft forever preferred_lft forever

fix ip regex in ip address format

---

dns/dnspod.py

因为dnspod返回的记录中使用@代表直接解析主域名　 {'id': '233', 'value': '3.1.1.1', 'enabled': '1', 'name': '@', 'line': '默认', 'line_id': '0', 'type': 'A', 'mx': '0'}

修复dnspod在无子域名，如xx.com时无法更新之前的记录，而总是创建新的记录

---

util/ip.py

fix #130 #150 #155 #156 
此PR做了以下修改: 
1. 修改IPv4地址API。为目前的IPv4 API增加了ie=utf-8的属性，强制API以UTF-8返回数据，解决目前版本获取IPv4地址时因[ERROR] 'utf-8' codec can't decode byte 0xb1 in position 73: invalid start byte导致IPv4地址获取失败的Bug。
2. 修改IPv6地址API。考虑到目前的IPv6 API支持HTTPS，因此本PR将IPv6 API改为和IPv4 API相同的HTTPS方式请求，降低可能存在的安全风险。

fix(ip): ip_public_api

---

.github/workflows/ci.yml

尝试使用 GitHub Actions 自动构建多架构的 Docker image。目前的策略是对 master 分支的 push 和 pull request 运行构建进行检查，对版本号 tag 运行构建并推送到 Docker Hub（同时更新 latest）。在推送之前需要在 Settings -> Secrets 中设置 DOCKER_USERNAME 和 DOCKER_PASSWORD 环境变量。

ci: Add GitHub Actions for Docker buildx

---

.release/create-task.bat

The script will run failed when the paths have spaces such as 'C:\Program Files\DDNS\ddns.exe'.
One possible solution is to add single quotes to each path.
Ref. https://stackoverflow.com/questions/10542313/powershell-and-schtask-with-task-that-has-a-space

Add single quotes in case the paths have spaces

---

.release/create-task.bat

Windows Task Scheduler is not CMD, the redirecting operator '>>' can only effect in CMD. So the operator will cause '0x2' error in Windows Task Scheduler.
My last commit https://github.com/NewFuture/DDNS/pull/208/commits/8ea0d5976de4a668e973e19548c8f2315f7b930f will force add the redirecting to the Win TS due to the double quotes in ```RUNCMD```, while the previous commit did not add log redirecting to Win TS as expected(Fig) and the log file was always empty.
One solution in this commit is to change the running program in Win TS from ddns.exe to cmd, then run ddns.exe in cmd. So that the Task can run as scheduled and the log can also be redirected.

Change ddns.exe to cmd in Windows Task Scheduler.

---

systemd.sh

Current shebang for `systemd.sh` has a syntax problem, which causes `[[` (string compare) could not work under `sh` shell environment.

Fix shebang typo

---

util/ip.py

example:
inet6 addr: fe80::f471:b5ff:fea0:2687/64 Scope:Link

fix regex_v6 string

---

run.py

Change 'EAMIL' to 'EMAIL' in generated template config file.

Fix typo in run.py

---

dns/alidns.py

https://github.com/NewFuture/DDNS/issues/231#issuecomment-820912617
use `replace('+','%20')` instead.

fix quote_via not compatible with Python2

---

README.md
run.py
util/config.py

配置可通过 命令行参数或者环境变量 #220 传递
`命令行参数` > `配置文件`  > `环境变量`
命令行 : `--key`
环境变量(DDNS 前缀): `${DDNS_KEY}` (或者全小写)
```
ddns [-h] [-v] [-c CONFIG] [--dns {alidns,cloudflare,dnscom,dnspod,dnspod_com,he,huaweidns,callback}] [--id ID] [--token TOKEN] [--ipv4 [IPV4 [IPV4 ...]]] [--ipv6 [IPV6 [IPV6 ...]]] [--index4 INDEX4] [--index6 INDEX6]
[--ttl TTL] [--proxy [PROXY [PROXY ...]]] [--debug [DEBUG]] [--cache [CACHE]]
optional arguments:
-h, --help            show this help message and exit
-v, --version         show program's version number and exit
-c CONFIG, --config CONFIG
run with config file [配置文件路径]
--dns {alidns,cloudflare,dnscom,dnspod,dnspod_com,he,huaweidns,callback}
DNS Provider [DNS服务提供商]
--id ID               api ID [授权账户]
--token TOKEN         api token or Secret key [授权访问凭证或密钥]
--ipv4 [IPV4 …
```

feat(config): supports cli argument and environment variables  to set config

---

dns/dnspod.py

Modify default request length for dnspod to 3000
Detail:
https://github.com/NewFuture/DDNS/issues/270#issuecomment-876920589

update dnspod.py for request length

---

README.md

这个功能还没实现，在一次PR中被错误引入
close #303 #259
related #144

(doc):remove interface 

---

README.md
run.py
schema/v2.8.json

根据 #143 提出的需求，本 PR 新增了自定义 DDNS 缓存文件的功能。
此处参考其他字段设计将 cache 字段更改为多类型字段，从而实现同一个字段既可以开关缓存又可以指定特定文件存放位置的功能。

feat(run): support custom cache file

---

run.py

原先代码存在逻辑问题，在cache配置为False情况下仍然创建了Cache结构体，导致认为创建出的Cache对象是合法对象，析构时open(False)抛出异常。
崩溃栈回溯如下，意思是调用了析构函数 `__del__` 时触发崩溃：
```
Exception ignored in: <function Cache.__del__ at 0x0000022A7420F160>
Traceback (most recent call last):
File "D:\python\python38\lib\site-packages\util\cache.py", line 140, in __del__
self.close()
File "D:\python\python38\lib\site-packages\util\cache.py", line 95, in close
self.sync()
File "D:\python\python38\lib\site-packages\util\cache.py", line 83, in sync
with open(self.__filename, 'wb') as data:
ValueError: Cannot open console input buffer for writing
```
跟踪代码，如果140行的cache是False，则142行的对象仍然被创建，因此144行的分支永远不可达。
```python
140    cache = get_config('cache', True)
141    cache = cache is True and path.join(gettempdir(), 'ddns.cache') or cache
142    cache = …
```

修复cache为False时的崩溃问题

---

util/ip.py

优先使用ip address 而非ifconfig，理由如下：
ifconfig 会先匹配到处于弃用（Deprecated）状态的v6 ip，不会把处于弃用的v6放到末尾，导致提交的dns v6解析记录为过期v6 ip。
而ip address获取到的前两个ip均为有效前缀v6 ip，可能是对lifetime 或者 ip 获得时间进行过排序
ipaddr 与 win 系统下的ipconfig ip顺序一致，符合“排序”期望
故希望在linux系统中，优先考虑使用ipaddress 而非 ifconfig

希望能更改linux系统下，index6 正则获取本地ip的命令优先级

---

README.md
doc/env.md
run.py
schema/v4.0.json
util/config.py

* Enhance environment variable handling to support arrays and simple parameter splitting.
* Improve logic and documentation
环境变量传递数组的方式 resolve #359 
```sh
export DDNS_INDEX6='["url:http://ipv6.icanhazip.com","public"，0]'
export DDNS_INDEX6=public
```

feat(config): 支持环境变量传递数组参数 Support array in environment variables and improve logic

---

docker/entrypoint.sh

兼容旧版本docker默认配置文件路径 并警告
resolve #486

fix(docker): compatibility of old default config path

---

.github/copilot-instructions.md
.github/instructions/python.instructions.md
.vscode/extensions.json
ddns/provider/_base.py
ddns/provider/alidns.py
ddns/provider/cloudflare.py
ddns/provider/huaweidns.py
doc/dev/provider.md
tests/test_provider_base.py
tests/test_provider_callback.py
tests/test_provider_cloudflare.py

This pull request introduces several enhancements and refactorings to the Python-based Dynamic DNS (DDNS) client. Key changes include the addition of development guidelines, refactoring of domain-related utility methods, updates to provider implementations, and adjustments to testing strategies for improved reliability and compatibility.
* [`.github/copilot-instructions.md`](diffhunk://#diff-227c2c26cb2ee0ce0f46a320fc48fbcbdf21801a57f59161b1d0861e8aad55f5R1-R81): Added comprehensive contribution guidelines, including coding standards, repository structure, and testing requirements. This provides clear instructions for developers working on the project.
* [`ddns/provider/_base.py`](diffhunk://#diff-0e27c1358dc2906e34ede404a295e1aa21eb5f95504b800a7b50aaca03165fecL623-R622): Refactored …

Refact(tests): improve base ,test,  and instructions

---

ddns/config/cli.py
tests/test_provider_callback.py
tests/test_util_http.py
tests/test_util_http_proxy_list.py

This pull request includes a minor update to the `ddns/config/cli.py` file. The change refines how the default configuration path is determined when the `config` attribute in `namespace` is a list.
* [`ddns/config/cli.py`](diffhunk://#diff-0723443ecdc201b3b39bfa650d35b046070cc766a6aee9947aed75144bf6d827L85-R86): Updated the logic for setting `config_path` to handle cases where `namespace.config` is a list, ensuring the first element of the list is used as the path.

fix(cli): new config default path
