- README.md
- dns/dnscom.py
- run.py
Hi，看了你这个工具非常棒，可惜没能支持DNSCOM，所以我就补充一下嘿嘿。
> 增加DNSCOM支持

- dns/cloudflare.py
只是测试了一下[#22](https://github.com/NewFuture/DDNS/issues/22)
测试了XXX.XXX.domain.com,没试过XXX.domian.net.cn
不过估计没问题
> Fix cloudflare zoneid

- dns/cloudflare.py
> Fix applying parameters to Cloudflare API on GET/DELETE requests

- dns/alidns.py
> fix(alidns): log action #51

- README.md
- dns/dnspod.py
- dns/dnspod_com.py
- run.py
> feat(index): 使用命令行输入作为目标IP #77

- README.md
- run.py
- schema/v2.json
- util/ip.py
* 更换默认IP提取API
* 支持自定义url `url:https:\\xxx.com`
#36 #85 #83
> feat(ip): 支持自定义URL

- util/ip.py
> fix(ip): default IP API

- dns/alidns.py
- dns/cloudflare.py
- dns/dnscom.py
- dns/dnspod.py
- run.py
> fix(config): fix #104 dnspod.com

- README.md
- dns/he.py
- schema.json
- schema/v2.json
Add support for [Hurricane Electric (he.net)](https://dns.he.net), a free DNS provider.
> Add support for HE.net Free DNS

- README.md
- dns/alidns.py
- dns/cloudflare.py
- dns/dnscom.py
- dns/dnspod.py
- run.py
- schema.json
- schema/v2.8.json
you can config TTL in next version
close #13 #14 #100
> feat(ttl): support ttl and update schema  #14

- .build/ddns.spec
- README.md
> 增加二进制版本的huaweidns

- dns/cloudflare.py
> fix(cloudflare): allow empty id to pass token

- .build/ddns.spec
> fix(spec): dnsprovider

- .release/create-task.sh
在Release版本自带的create-task.sh文件中修复 #27 所出现的问题
> fix(task) fix #27 on release

- .build/ddns.spec
- README.md
- dns/callback.py
- schema/v2.8.json
根据 #163 的讨论 和 #103 #148 提出的需求，本PR通过新增DNS Provider实现了检测IP变动后支持触发回调API的功能。
> feat(dnsprovider): support custom callback api

- .release/create_task.systemd.sh
Add systemd task creator, which is easier and has more function than the original cron one.
Solve: https://github.com/NewFuture/DDNS/issues/174
> Feature: Add systemd task creator

- .release/create_task.systemd.sh
Fix: service permanent fail if timeout
> Fix: service permanent fail if timeout

- README.md
补充被提及的但是不在上面的 Cloudflare，并对原有文本进行格式化
> reformat(readme): 详细配置 -> 配置参数表 -> key -> dns 行

- dns/callback.py
> fix callback #222

- dns/alidns.py
> fix #231 change signature() encoding method to quote() to meet docs of alidns

- schema/v2.8.json
> fix #173 domain pattern to match start with *

- Dockerfile
- README.md
- entrypoint.sh
Solving #276. Updating DDNS using environment variables and configuration file have been tested.
> Support environment variables in Docker image

- dns/cloudflare.py
> feat(cf): keep proxied config in cloudflare

- dns/dnspod_com.py
change user_token to login_token
> fix(dnspod_com): resolve #286

- .github/workflows/build.yml
- .github/workflows/publish.yml
- run.py
python2 bundle size is smaller
> using py2 for bundles

- schema/v2.8.json
> fix: schema add cache property

- util/ip.py
修改提供公网ip查询服务的api，原先的api不稳定
#367
> 修改不稳定的公网IP查询服务api

- run.py
https://github.com/NewFuture/DDNS/commit/8f184468f99c60c010e2890088c5dbfdb37205a8 修改了PROXY的位置到Config下，但设置的地方没有同步修改
> fix: proxy config

- run.py
> fix(run): domain name uniformly lowercase to avoid problems

- run.py
> get_ip whith try/catch

- .github/workflows/build.yml
- .github/workflows/publish.yml
* linux/amd64,
* linux/amd64/v2,
* linux/amd64/v3,
* linux/arm64,
* linux/riscv64,
* linux/ppc64le,
* linux/s390x,
* linux/386,
* linux/mips64le,
* linux/mips64,
* linux/loong64,
* linux/arm/v7,
* linux/arm/v6
> feat(docker): more architecture platforms

- setup.py
* Update setup.py added python2 back
* Apply suggestions from code review
> Reintroduce Python 2 Compatibility in setup.py (#460)

- .gitignore
- .vscode/extensions.json
- README.md
- run.py
- schema/v2.8.json
- schema/v4.0.json
- util/config.py
> 重构日志配置，移除调试模式，添加日志级别和输出文件选项；更新配置文件模式至v4.0

- .github/workflows/build.yml
- .github/workflows/publish.yml
- run.py
使用amd 和 arm 直接编译，不使用qemu加快PR的编译速度
> build(docker): 优化build检查和push tag

- ddns/__main__.py
log 
* DEBUG 打印详细函数名
* INFO 打印模块
* WARNING 只打印时间
> feat(log): add funcName in log

- README.md
- ddns/provider/_base.py
- ddns/provider/alidns.py
- ddns/provider/cloudflare.py
- ddns/provider/dnscom.py
- ddns/provider/he.py
- ddns/provider/huaweidns.py
- ddns/provider/tencentcloud.py
- doc/dev/provider.md
- tests/test_hmac_sha256_authorization.py
- tests/test_provider_alidns.py
- tests/test_provider_callback.py
- tests/test_provider_huaweidns.py
- tests/test_provider_tencentcloud.py
This pull request introduces significant enhancements to the DDNS project, focusing on improving security through HMAC-SHA256-based authentication, refactoring repetitive code, and updating documentation. The most notable changes include the addition of reusable cryptographic functions, the adoption of a universal HMAC-SHA256 authorization mechanism across multiple providers, and the refinement of provider-specific implementations. Documentation updates also provide clearer guidance for developers.
* Added reusable cryptographic functions `hmac_sha256`, `sha256_hash`, and `hmac_sha256_authorization` in `ddns/provider/_base.py` to standardize HMAC-SHA256-based authentication for cloud providers.
* Updated `README.md` to highlight providers using HMAC-SHA256 authentication for …
> Refactor(base): HMAC-SHA256 signature logic

- docker/glibc.Dockerfile
- docker/test-in-docker.sh
- tests/config/callback.json
- tests/config/debug.json
* base-builder: 替换 archive 源(正式源已下线)
* builder: build中移除 apt-add
* docker 这运行真实测试
> chore(docker): Update glibc.Dockerfile

- .github/patch.py
- .github/workflows/build.yml
- .github/workflows/publish.yml
- .vscode/settings.json
- ddns/__main__.py
- ddns/config/cli.py
- ddns/scheduler/__init__.py
- ddns/scheduler/_base.py
- ddns/scheduler/cron.py
- ddns/scheduler/launchd.py
- ddns/scheduler/schtasks.py
- ddns/scheduler/systemd.py
- ddns/util/fileio.py
- ddns/util/try_run.py
- docker/Dockerfile
- run.py
- tests/test_scheduler_cron.py
- tests/test_scheduler_launchd.py
- tests/test_scheduler_schtasks.py
- tests/test_scheduler_systemd.py
This pull request introduces several improvements and refactorings to the DDNS project, primarily focused on scheduler handling, Docker build compatibility, and platform-specific behaviors. The main changes include refactoring scheduler subprocess logic, adding support for Docker builds by removing scheduler components, and improving Windows output handling. Additionally, workflow files and VSCode settings are updated to support these changes.
**Scheduler refactoring and platform detection:**
* Refactored all scheduler classes (`cron.py`, `launchd.py`, `schtasks.py`) to use a new `try_run` utility for subprocess execution instead of custom `_run_command` methods, improving reliability and consistency of external command calls. (`[[1]](diffhunk://#diff-04d0759bcb3e9f91715c6b02318943f238783a …
> fix(scheduler ): scheduler path and check
